# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSG Build to Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # cache the dependencies from any node_modules directory
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/package-lock.json
            **/.production
          key: node_modules-${{ hashFiles('**/package.json') }}

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build --cache

      - name: Send to Github
        run: |
          git branch master -f
          git checkout master
          git add ssg -f
          git config --global user.name "BrunoLM"
          git config --global user.email "brunolm7@gmail.com"
          git commit -m ":rocket: New SSG Build"
          git subtree push -f --prefix ssg origin master
